### ISSUE TITLE
make conda package

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/mofchecker#103]
## Feature description

We already depend on openbabel, and maybe will also depend on zeo++ (#56). For users it would be much more convenient if they can just get everything with one conda install command. 

## Implementation idea

Make a conda forge recipe

**Comment by kjappelbaum** [comment]
https://github.com/conda-forge/staged-recipes/pull/14337

**Comment by ltalirz** [comment]
I guess this can be closed ;-) https://github.com/conda-forge/staged-recipes/pull/14337
