### ISSUE TITLE
CI only runs on `master` - intentional?

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/mofchecker#162]
https://github.com/kjappelbaum/mofchecker/blob/18fe1ca83fe10f3da8ad70afd7a886814b67be13/.github/workflows/python-package.yml#L7-L8

This means e.g. that CI won't run on feature branches on forks before making a pull request

**Comment by kjappelbaum** [comment]
no, it is just me being stupid

**Comment by kjappelbaum** [comment]
fixed already
