### ISSUE TITLE
Citation reference

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofchecker#222]
You should add a way to reference this work, even if just a Zenodo DOI :)

**Comment by kjappelbaum** [comment]
Thanks for bringing this up. 

Yeah, I think it is not good enough for JOSS (which was the original goal). Hence I'll now mint a Zenodo DOI

**Comment by kjappelbaum** [comment]
Does https://github.com/kjappelbaum/mofchecker/blob/main/CITATION.cff help?

**Comment by Andrew-S-Rosen** [comment]
Looks great!
