### ISSUE TITLE
Export some variable with information about expected value and help

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/mofchecker#41]
## Feature description

It would be great if we could import some dict that maps the keys of the checks to the expected ideal value and some description of what they do.

## Implementation idea

We can just add an attribute to the instance

## Alternatives

Variable that is declared outside the class.

**Comment by kjappelbaum** [comment]
closed in https://github.com/kjappelbaum/mofchecker/pull/43

**Comment by ltalirz** [comment]
close?
