### ISSUE TITLE
Overly aggressive underbonded N checker

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofchecker#48]
Hey Kevin! I took four CIFs from the CSD: [`ABAXIN`](https://www.ccdc.cam.ac.uk/structures/Search?Ccdcid=abaxin&DatabaseToSearch=Published), [`ABAXOT`](https://www.ccdc.cam.ac.uk/structures/Search?Ccdcid=abaxot&DatabaseToSearch=Published), [`ABAXUZ`](https://www.ccdc.cam.ac.uk/structures/Search?Ccdcid=abaxuz&DatabaseToSearch=Published), and [`ABAZAF`](https://www.ccdc.cam.ac.uk/structures/Search?Ccdcid=abazaf&DatabaseToSearch=Published). Running all 4 through the MOF Checker yields `True` flags for `has_undercoordinated_n`. Unless I'm mistaken, it appears that the coordination number on the N is okay in these instances. For instance, the structure below of `ABAXUZ` (based on the drawing at least) has an appropriate number of bonds for the N atom, but it's nonetheless flagged. I attached the (DFT-optimized) CIF for that one here. Let me know if I'm off the mark! Apologies for not just finding the cause myself -- I'm a bit short on time these days. Note that this was all done using v.0.3.1.

![image](https://user-images.githubusercontent.com/8674072/102001176-7fbffb00-3cb4-11eb-98b2-1f83b6e01315.png)
[ABAXUZ_FSR.cif.txt](https://github.com/kjappelbaum/mofchecker/files/5684080/ABAXUZ_FSR.cif.txt)

**Comment by kjappelbaum** [comment]
Many thanks for the report, will give it a look!

**Comment by kjappelbaum** [comment]
Thanks for the report, keep them coming! 😆  
Your example is now a test case. 

I'll improve some other checks and will make a new release

**Comment by arosen93** [comment]
Talk about fast turnaround there! Glad to help. I'll let you know if I spot any other cases worth sharing.

**Comment by arosen93** [comment]
Here's another case that might be worth patching:

[`ABIQAE`], [`ABITUA`], [`ABOTUJ`], [`ABOVOF`], etc. Anytime there are NCS functional groups, it flags the N as undercoordinated. Or at least, I think that's the common theme. I attached one of the CIFs below.

[ABOVOF_FSR.txt](https://github.com/kjappelbaum/mofchecker/files/5687260/ABOVOF_FSR.txt)
