### ISSUE TITLE
check if porous

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/mofchecker#56]
- ideally using simply heuristic and not running zeo++ to avoid the dependency (yes, we could but this into the wheel, but keeping it simple sounds better to me)

**Comment by kjappelbaum** [comment]
https://github.com/kaitrepte/porE is potentially "easier" as dependency

**Comment by kjappelbaum** [comment]
CoRE uses pore limiting diameter > 2.4 Angstrom

**Comment by ltalirz** [comment]
just mentioning that zeo++ is now quite easy to install using `conda install -c conda-forge zeopp-lsmo`

**Comment by kjappelbaum** [comment]
hm ... maybe we can use it as an extra ...
