### ISSUE TITLE
Minor improvement to printed warnings

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofchecker#59]
1. Every time a CN3 is found, mofchecker prints that it found one. Probably a leftover from a debug session. See [here](https://github.com/kjappelbaum/mofchecker/blob/3a4be5ed2a0caf7b11f388a80029e583ca2bd199/mofchecker/__init__.py#L265).

2. Every time a new MOF is checked, the waring about OpenBabel is printed. See [here](https://github.com/kjappelbaum/mofchecker/blob/3a4be5ed2a0caf7b11f388a80029e583ca2bd199/mofchecker/utils.py#L50). It might be more user-friendly to move that to the `__init__` or some place that it'd only be called once. Also, `conda install openbabel` should be changed to `conda install -c openbabel openbabel` just for completeness.

**Comment by kjappelbaum** [comment]
>Probably a leftover from a debug session.  

yep :D 

> Every time a new MOF is checked, the waring about OpenBabel is printed. See here. It might be more user-friendly to move that to the __init__ or some place that it'd only be called once. Also, conda install openbabel should be changed to conda install -c openbabel openbabel just for completeness.

great suggestion!
