### ISSUE TITLE
requires networkx 2.5

### ISSUE THREAD

**Issue by ltalirz** [kjappelbaum/mofchecker#82]
## Steps to reproduce the problem

installed mofchecker from latest git in existing environment with older pymatgen version & networkx 2.4

Got error `No module named 'networkx.algorithms.graph_hashing'`

Just add `networkx>=2.5` to the requirements

**Comment by kjappelbaum** [comment]
hopefully closed by https://github.com/kjappelbaum/mofchecker/commit/00f0afbc22f9340ecb2980ed5211778efafa8433, thanks!
